### ISSUE TITLE
Unable to Import .vmf map into Roblox Studio (HttpError: ConnectFail)

### ISSUE THREAD

**Issue by Hurtenpro** [duckymomo360/roblox-source-engine-map-importer#1]
So basically what I am doing:

I download everything, I install VSS,

https://user-images.githubusercontent.com/114229581/192036529-cf12c324-e347-4323-b86a-ce1224aab275.mp4

I get my map (d1_c17_04_d) in .bsp, I decompile it and turn it into a .vmf (via. BSPSource)
I have MeshConverter open, VMFImporter.rbxl open and have the plugin open and then feed the .vmf file into the plugin and I get ''HttpError: ConnectFail''.

My friend who imports the maps regularly doesn't know what the problem is and maybe someone who knows how to do this can help me with this please?

**Comment by duckymomo360** [comment]
This project is outdated and kind of broken. I sugguest you use this one instead. It works so much better. https://github.com/MaximumADHD/Source2Roblox

**Comment by Hurtenpro** [comment]
> 

Still able to help me?

**Comment by duckymomo360** [comment]
No sorry
